# Generated by Django 3.2.8 on 2021-11-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_productdata_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='owner',
            field=models.CharField(default='Google', max_length=50),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='stock',
            field=models.CharField(default=100, max_length=100),
        ),
    ]
