# Generated by Django 3.2.8 on 2021-11-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_cartdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartData',
        ),
    ]
