# Generated by Django 3.2.8 on 2021-11-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobileNumber', models.CharField(max_length=10)),
                ('pin', models.CharField(max_length=10)),
                ('locality', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=50)),
                ('Address_Type', models.CharField(max_length=6)),
            ],
        ),
    ]
