# Generated by Django 3.2.8 on 2021-11-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_cartdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('productName', models.CharField(max_length=100)),
                ('userId', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cartdata',
            name='userId',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
