# Generated by Django 3.2.8 on 2021-11-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0003_auto_20211106_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='landmark',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='userId',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
